version: '3'
services:
  main:
    build:
        context: .
        args:
            - http_proxy
            - https_proxy
            - no_proxy
    image: tmp_centos5_x86
    volumes:
    - ./output:/output